{{- if .Values.deployRegistrySecret -}}
{{- $appname := printf "%s" (include "name" .) -}}
{{- $vaultUrl := printf "%s" (include "vaultUrl" .) -}}
{{- $vaultRole := printf "%s" (include "vaultRole" .) -}}
{{- $vaultAuthPath := printf "%s" (include "vaultAuthPath" .) -}}
{{- $env := printf "%s" (include "environment" .) -}}
{{- $vaultNamespace := printf "%s" (include "vaultNamespace" .) -}}
{{- $dockerUser := printf "vault:secret/data/infra/%s/docker-registry/%s#DOCKER_REPO_USER" $vaultNamespace $env }}
{{- $dockerPass := printf "vault:secret/data/infra/%s/docker-registry/%s#DOCKER_REPO_PASS" $vaultNamespace $env }}
{{- $dockerAddr := (split "/" .Values.image.repository)._0 }}
{{- $authBasic := printf "%s:%s" $dockerUser $dockerPass | b64enc}}
{{- $dockerSecret := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\": \"%s\"}}}" $dockerAddr $dockerUser $dockerPass $authBasic}}

apiVersion: v1
data:
  .dockerconfigjson: {{ $dockerSecret | b64enc }}
kind: Secret
metadata:
 name: regsecret-{{ $appname }}
 annotations:
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/sync-wave: "-5"
    vault.security.banzaicloud.io/vault-addr: {{ $vaultUrl }}
    vault.security.banzaicloud.io/vault-role: {{ $vaultRole }}
    vault.security.banzaicloud.io/vault-path: {{ $vaultAuthPath }}
    vault.security.banzaicloud.io/vault-env-daemon: "true"
    vaultInjectionChecksum: {{ printf "%s" $dockerSecret | sha256sum }}
type: kubernetes.io/dockerconfigjson
{{- end -}}
