{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceAccountName" . }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end -}}